### PR TITLE
Celestron aux refactor (monitoring PR)

### PR DESCRIPTION
**Pull request by jochym**

### CODE REVIEW

**Comment by jochym** [comment]
@knro I am running a private PR here against my fork to watch your work. Let me know, please, when it is going to be ready for first compile and test.

**Comment by jochym** [comment]
@knro You have done a lot. However, It seems the driver is not tracking in Az. I have compiled the recent version (b3fddb4) - this is a first one I am testing, so I do not know if this is recent or not. See this log fragment:
```
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Axis1 encoder    4908650 -> AZ 105.3282° "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Axis2 encoder    4170589 -> AL 89.4911° "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Mount -> Sky RA: 21:28:52 DE: 50:51:46 AZ: 105:24:27 AL: 89:29:37 HA: 10:39:02 Pier: NA "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AZ Now: 4908650 Target: 12146708 Offset: 7238058 Rate: 100000.00 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AZ P: 579044640.000000 I: 0.000000 D: -0.000000 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AL Now: 4170589 Target: 4170608 Offset: 19 Rate: -480.00 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AL P: 1520.000000 I: -2000.000000 D: -0.000000 "
org.kde.kstars.indi: Celestron AUX : "[CAUX] CMD <MC_SET_NEG_GUIDERATE>  APP ->  ALT [00 01 E0] "
org.kde.kstars.indi: Celestron AUX : "[CSER] CMD <3B 06 20 11 07 00 01 E0 E1> "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 06 20 11 07 00 01 E0 E1> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_SET_NEG_GUIDERATE>  APP ->  ALT [00 01 E0] "
org.kde.kstars.indi: Celestron AUX : "[CAUX] Got msg not for me (ALT). Ignoring. "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 03 11 20 07 C5> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_SET_NEG_GUIDERATE>  ALT ->  APP "
org.kde.kstars.indi: Celestron AUX : "[CAUX] CMD <MC_GET_POSITION>  APP ->  AZM "
org.kde.kstars.indi: Celestron AUX : "[CSER] CMD <3B 03 20 10 01 CC> "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 03 20 10 01 CC> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  APP ->  AZM "
org.kde.kstars.indi: Celestron AUX : "[CAUX] Got msg not for me (AZM). Ignoring. "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 06 10 20 01 4A EB DE B6> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  AZM ->  APP [4A EB DE] "
org.kde.kstars.indi: Celestron AUX : "[CAUX] CMD <MC_GET_POSITION>  APP ->  ALT "
org.kde.kstars.indi: Celestron AUX : "[CSER] CMD <3B 03 20 11 01 CB> "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 03 20 11 01 CB> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  APP ->  ALT "
org.kde.kstars.indi: Celestron AUX : "[CAUX] Got msg not for me (ALT). Ignoring. "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 06 11 20 01 3F A3 21 C5> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  ALT ->  APP [3F A3 21] "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Axis1 encoder    4910046 -> AZ 105.3582° "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Axis2 encoder    4170529 -> AL 89.4898° "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Mount -> Sky RA: 21:28:54 DE: 50:51:44 AZ: 105:26:15 AL: 89:29:32 HA: 10:39:00 Pier: NA "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AZ Now: 4910046 Target: 12149334 Offset: 7239288 Rate: 100000.00 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AZ P: 579143040.000000 I: 0.000000 D: -0.000000 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AL Now: 4170529 Target: 4170475 Offset: -53 Rate: -6320.00 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AL P: -4320.000000 I: -2000.000000 D: 0.000000 "
org.kde.kstars.indi: Celestron AUX : "[CAUX] CMD <MC_SET_NEG_GUIDERATE>  APP ->  ALT [00 18 B0] "
org.kde.kstars.indi: Celestron AUX : "[CSER] CMD <3B 06 20 11 07 00 18 B0 FA> "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 06 20 11 07 00 18 B0 FA> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_SET_NEG_GUIDERATE>  APP ->  ALT [00 18 B0] "
org.kde.kstars.indi: Celestron AUX : "[CAUX] Got msg not for me (ALT). Ignoring. "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 03 11 20 07 C5> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_SET_NEG_GUIDERATE>  ALT ->  APP "
org.kde.kstars.indi: Celestron AUX : "[CAUX] CMD <MC_GET_POSITION>  APP ->  AZM "
org.kde.kstars.indi: Celestron AUX : "[CSER] CMD <3B 03 20 10 01 CC> "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 03 20 10 01 CC> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  APP ->  AZM "
org.kde.kstars.indi: Celestron AUX : "[CAUX] Got msg not for me (AZM). Ignoring. "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 06 10 20 01 4A F1 51 3D> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  AZM ->  APP [4A F1 51] "
org.kde.kstars.indi: Celestron AUX : "[CAUX] CMD <MC_GET_POSITION>  APP ->  ALT "
org.kde.kstars.indi: Celestron AUX : "[CSER] CMD <3B 03 20 11 01 CB> "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 03 20 11 01 CB> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  APP ->  ALT "
org.kde.kstars.indi: Celestron AUX : "[CAUX] Got msg not for me (ALT). Ignoring. "
org.kde.kstars.indi: Celestron AUX : "[CSER] RES <3B 06 11 20 01 3F A2 CD 1A> "
org.kde.kstars.indi: Celestron AUX : "[CAUX] RES <MC_GET_POSITION>  ALT ->  APP [3F A2 CD] "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Axis1 encoder    4911441 -> AZ 105.3881° "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Axis2 encoder    4170445 -> AL 89.4880° "
org.kde.kstars.indi: Celestron AUX : "[ALIGNMENT] Mount -> Sky RA: 21:28:56 DE: 50:51:42 AZ: 105:28:02 AL: 89:29:26 HA: 10:38:59 Pier: NA "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AZ Now: 4911441 Target: 12151931 Offset: 7240490 Rate: 100000.00 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AZ P: 579239200.000000 I: 0.000000 D: -0.000000 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AL Now: 4170445 Target: 4170342 Offset: -102 Rate: -10240.00 "
org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AL P: -8240.000000 I: -2000.000000 D: -0.000000 "
```
There are only ALT guide rate commands in the log and it was tracking object close to zenith. It should be tracking in Az like crazy... The code in tracking seems ok but i think the trackByRate may be skipping tracking i  AZ due to detection of unchanged rate (just a suspicion).

**Comment by knro** [comment]
Thanks for the feedback. It is tracking in AZ, however, the different is HUGE:

org.kde.kstars.indi: Celestron AUX : "[DEBUG] Tracking AZ Now: 4911441 Target: 12151931 Offset: 7240490 Rate: 100000.00 "

With this large offset, it's never going to be able to catch up. Need to stop and slew again. Not sure how it got there to begin with. Maybe runaway after a while?

**Comment by jochym** [comment]
1) Shall I close a copy at (https://github.com/indilib/indi-3rdparty/issues/510) ?
2) It is supposed to be large - this is close to the zenith. But it is not sending any Az guide commands (did I miss it?)
3) In my tests, there was also no az tracking in moderate altitudes. Do you want me to retest in a more *normal* case and post the results?

**Comment by jochym** [comment]
This particular test was:
1. Point to the object close to zenith just before transit
2. Monitor the tracking while it transits

This was my standard test for the driver, and it was able to track (barely) up to Alt: approx 89deg (depending on version). The log is a fragment after few minutes when I was sure it does not track.

I am happy to run further tests - just say so.

**Comment by knro** [comment]
Ok just tried against a couple of targets (didn't wait for transit yet) and it seems tracking is OK. can you attach your file for the full log? or when it starts to go crazy and lose tracking?

**Comment by jochym** [comment]
Ok. Maybe I just got unlucky or something. I will retest more rigorously and attach a full log. I guess we are tracking here and I will close the issue on indi repo.

**Comment by knro** [comment]
Actually, I found an issue where it would begin to fluctuate once the offset flips sign. I added a "settle" time once this happen to prevent oscillations around zero and it appears to work, so please reset the latest commits. If you have a better method for PID control let me know what we can do here.

**Comment by jochym** [comment]
I fixed some problems with using simulator. But I cannot reproduce the no-az tracking yet. However, I have noticed worrying movements in alt over negative altitudes and altitudes above 90deg in Axis2 box. I will investigate this and come back to you if I get a reproducible case.

**Comment by jochym** [comment]
I guess it is time for another testing round @knro ? Unfortunately, the weather is bad, and I have only AltAz mount. Maybe Fabrizio can help with the EQ mount?
Let me know if I should run any particular tests.

**Comment by knro** [comment]
Thanks, just use it normally. If Fabrizio can help with this it would be great, I asked on the forum for access to Equatorial mounts.

**Pull request closed without merging**
